### ISSUE TITLE
Arena Bounds Dosn't Work

### ISSUE THREAD

**Issue by ily-7** [TroDerp/EggWars#6]
After I set arena Bounds And Join The Match I Cant Place Block.

I use: Purpur 1.19.4 1985 
![image](https://github.com/TroDerp/EggWars/assets/118382413/8f92b070-2fa0-463c-8ca4-94f1dea5e713)

You Can Message Me In Discord I Want Make This Pl Better: _ily7_#6596
![image](https://github.com/TroDerp/EggWars/assets/118382413/999fbd1f-a2dc-426d-8d0e-151426c6a8e8)

**Comment by TroDerp** [comment]
This is fixed as of commit 2883fa7, but I didn't release yet because I'm waiting for spigot 1.20 to fully come out to add support. Until then, you can set up bounds using the command `/ews setBounds <xStart> <yStart> <zStart> <xEnd> <yEnd> <zEnd>` - the bug didn't happen if you use this way.
Thank you for reporting anyway 😅 (I will accept your f request)

**Comment by ily-7** [comment]
Problem solved On EggWars 6.1.0 (Pre)
